apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: karen-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/volume
