apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  namespace: karen-test
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  volumeName: pv 